version: '3'
services:
  envoy:
    build: .
    network_mode: 'host'
    ports:
      - "8081:8081"
    container_name: proxy-envoy-container

  app:
    build: 
      context: .
      dockerfile: Dockerfile-node
    network_mode: 'host'
    ports:
      - "50051:50051"
    volumes:
      - .:/usr/app
    container_name: password-service-container
    command: yarn start
    environment:
      - SERVER_ADDRESS=0.0.0.0:50051
networks:
  overlay:
